### ISSUE TITLE
Selecting Program In TurboRisk fails

### ISSUE THREAD

**Issue by brian-scott-andrews** [brian-scott-andrews/TurboRisk#11]
![Program Select](https://user-images.githubusercontent.com/10187492/67164955-f1b0e480-f33c-11e9-80de-84de20b639c7.PNG)

**Comment by brian-scott-andrews** [comment]
![Program select subroutine](https://user-images.githubusercontent.com/10187492/67165581-1f4d5c00-f344-11e9-8d97-35060d9c8688.PNG)
![select error debug](https://user-images.githubusercontent.com/10187492/67165582-1fe5f280-f344-11e9-9694-400852c56cf0.PNG)

**Comment by agreatnate** [comment]
Yes, this dialog box wasn't sufficiently tested in Windows apparently.  There were two problems: 
 - The slash in 'players/*.trp'  needed to be changed to a PathDelim variable.
 - The writeln command doesn't work in Windows for non-console programs (it works fine and prints to the console in Linux).  Both should be fixed now.

**Comment by brian-scott-andrews** [comment]
Verified correct operation of selecting file. 

Bug of only reading the first file in the players directory was also resolved
